### Read every table from the database and look at each one on its own

In [53]:
import pandas as pd
from sqlalchemy import create_engine

In [54]:
engine=create_engine("mysql+pymysql://root:mysecretpassword@localhost:3306/olist_db")

In [55]:
# customer table
customers_table=pd.read_sql_table("customers",con=engine)
customers_table.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [56]:
# Read Orders table
orders_table=pd.read_sql_table("orders",con=engine)
orders_table.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [57]:
# Read Items table
items_table=pd.read_sql_table("items",con=engine)
items_table.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [58]:
# Read Products table
products_table=pd.read_sql_table("products",con=engine)
products_table.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [59]:
# Read Pyments table
pyments_table=pd.read_sql_table("pyments",con=engine)
pyments_table.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [60]:
# Read Reviews table
reviews_table=pd.read_sql_table("reviews",con=engine)
reviews_table.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [61]:
# Read Sellers table
sellers_table=pd.read_sql_table("sellers",con=engine)
sellers_table.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [62]:
# Read Geolocation table
geolocation_table=pd.read_sql_table("geolocation",con=engine)
geolocation_table.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

### Check row counts, keys, duplicates, and what one row means in each table

In [63]:
# Customers Table
print(f"Costumers row counts is: {len(customers_table)}")
print(f"customer city mode: {customers_table['customer_city'].mode()[0]}")
for col in customers_table.columns:
    is_unique=customers_table[col].is_unique
    has_nulls=customers_table[col].isnull().sum()
    is_duplicated=customers_table[col].duplicated().sum()
    print(f"{col}: Unique= {is_unique} | Null = {has_nulls} | Duplicated= {is_duplicated}")

Costumers row counts is: 99441
customer city mode: sao paulo
customer_id: Unique= True | Null = 0 | Duplicated= 0
customer_unique_id: Unique= False | Null = 0 | Duplicated= 3345
customer_zip_code_prefix: Unique= False | Null = 0 | Duplicated= 84447
customer_city: Unique= False | Null = 0 | Duplicated= 95322
customer_state: Unique= False | Null = 0 | Duplicated= 99414

In [64]:
# Order Table
print(f"Orders row counts is: {len(orders_table)}")
print(f"Orders status mode: {orders_table['order_status'].mode()[0]}")
for col in orders_table.columns:
   is_unique=orders_table[col].is_unique
   has_nulls=orders_table[col].isnull().sum()
   is_duplicated=orders_table[col].duplicated().sum()
   print(f"{col}: Unique= {is_unique} | Null = {has_nulls} | Duplicated= {is_duplicated}")

Orders row counts is: 99441
Orders status mode: delivered
order_id: Unique= True | Null = 0 | Duplicated= 0
customer_id: Unique= True | Null = 0 | Duplicated= 0
order_status: Unique= False | Null = 0 | Duplicated= 99433
order_purchase_timestamp: Unique= False | Null = 0 | Duplicated= 566
order_approved_at: Unique= False | Null = 160 | Duplicated= 8707
order_delivered_carrier_date: Unique= False | Null = 1783 | Duplicated= 18422
order_delivered_customer_date: Unique= False | Null = 2965 | Duplicated= 3776
order_estimated_delivery_date: Unique= False | Null = 0 | Duplicated= 98982

In [65]:
# Items Table
print(f"Items row counts is: {len(items_table)}")
print(f"Items Price mean: {items_table['price'].mean():.4f}")
for col in items_table.columns:
    is_unique=items_table[col].is_unique
    has_nulls=items_table[col].isnull().sum()
    is_duplicated=items_table[col].duplicated().sum()
    print(f"{col}: Unique= {is_unique} | Null = {has_nulls} | Duplicated= {is_duplicated}")

Items row counts is: 112650
Items Price mean: 120.6537
order_id: Unique= False | Null = 0 | Duplicated= 13984
order_item_id: Unique= False | Null = 0 | Duplicated= 112629
product_id: Unique= False | Null = 0 | Duplicated= 79699
seller_id: Unique= False | Null = 0 | Duplicated= 109555
shipping_limit_date: Unique= False | Null = 0 | Duplicated= 19332
price: Unique= False | Null = 0 | Duplicated= 106682
freight_value: Unique= False | Null = 0 | Duplicated= 105651

In [66]:
# Products Table
print(f"Products row counts is: {len(products_table)}")
print(f"Products Photo qty mean: {products_table['product_photos_qty'].mean():.4f}")
for col in products_table.columns:
    is_unique=products_table[col].is_unique
    has_nulls=products_table[col].isnull().sum()
    is_duplicated=products_table[col].duplicated().sum()
    print(f"{col}: Unique= {is_unique} | Null = {has_nulls} | Duplicated= {is_duplicated}")

Products row counts is: 32951
Products Photo qty mean: 2.1890
product_id: Unique= True | Null = 0 | Duplicated= 0
product_category_name: Unique= False | Null = 610 | Duplicated= 32877
product_name_lenght: Unique= False | Null = 610 | Duplicated= 32884
product_description_lenght: Unique= False | Null = 610 | Duplicated= 29990
product_photos_qty: Unique= False | Null = 610 | Duplicated= 32931
product_weight_g: Unique= False | Null = 2 | Duplicated= 30746
product_length_cm: Unique= False | Null = 2 | Duplicated= 32851
product_height_cm: Unique= False | Null = 2 | Duplicated= 32848
product_width_cm: Unique= False | Null = 2 | Duplicated= 32855

In [67]:
# Pyments Table
print(f"Pyments row counts is: {len(pyments_table)}")
print(f"Pyments value mean: {pyments_table['payment_value'].mean():.4f}")
for col in pyments_table.columns:
    is_unique=pyments_table[col].is_unique
    has_nulls=pyments_table[col].isnull().sum()
    is_duplicated=pyments_table[col].duplicated().sum()
    print(f"{col}: Unique= {is_unique} | Null = {has_nulls} | Duplicated= {is_duplicated}")

Pyments row counts is: 103886
Pyments value mean: 154.1004
order_id: Unique= False | Null = 0 | Duplicated= 4446
payment_sequential: Unique= False | Null = 0 | Duplicated= 103857
payment_type: Unique= False | Null = 0 | Duplicated= 103881
payment_installments: Unique= False | Null = 0 | Duplicated= 103862
payment_value: Unique= False | Null = 0 | Duplicated= 74809

In [68]:
# Reviews Table
print(f"Reviews row counts is: {len(reviews_table)}")
print(f"Reviews Score mean: {reviews_table['review_score'].mean():.4f}")
for col in reviews_table.columns:
    is_unique=reviews_table[col].is_unique
    has_nulls=reviews_table[col].isnull().sum()
    is_duplicated=reviews_table[col].duplicated().sum()
    print(f"{col}: Unique= {is_unique} | Null = {has_nulls} | Duplicated= {is_duplicated}")

Reviews row counts is: 99224
Reviews Score mean: 4.0864
review_id: Unique= False | Null = 0 | Duplicated= 814
order_id: Unique= False | Null = 0 | Duplicated= 551
review_score: Unique= False | Null = 0 | Duplicated= 99219
review_comment_title: Unique= False | Null = 87656 | Duplicated= 94696
review_comment_message: Unique= False | Null = 58247 | Duplicated= 63064
review_creation_date: Unique= False | Null = 0 | Duplicated= 98588
review_answer_timestamp: Unique= False | Null = 0 | Duplicated= 976

In [69]:
# Sellers Table
print(f"Sellers row counts is: {len(sellers_table)}")
print(f"Sellers city mode: {sellers_table['seller_city'].mode()[0]}")
for col in sellers_table.columns:
   is_unique=sellers_table[col].is_unique
   has_nulls=sellers_table[col].isnull().sum()
   is_duplicated=sellers_table[col].duplicated().sum()
   print(f"{col}: Unique= {is_unique} | Null = {has_nulls} | Duplicated= {is_duplicated}")

Sellers row counts is: 3095
Sellers city mode: sao paulo
seller_id: Unique= True | Null = 0 | Duplicated= 0
seller_zip_code_prefix: Unique= False | Null = 0 | Duplicated= 849
seller_city: Unique= False | Null = 0 | Duplicated= 2484
seller_state: Unique= False | Null = 0 | Duplicated= 3072

In [70]:
# Geolocation Table
print(f"Geolocation row counts is: {len(geolocation_table)}")
print(f"Geolocation city mode: {geolocation_table['geolocation_city'].mode()[0]}")
for col in geolocation_table.columns:
   is_unique=geolocation_table[col].is_unique
   has_nulls=geolocation_table[col].isnull().sum()
   is_duplicated=geolocation_table[col].duplicated().sum()
   print(f"{col}: Unique= {is_unique} | Null = {has_nulls} | Duplicated= {is_duplicated}")

Geolocation row counts is: 1000163
Geolocation city mode: sao paulo
geolocation_zip_code_prefix: Unique= False | Null = 0 | Duplicated= 981148
geolocation_lat: Unique= False | Null = 0 | Duplicated= 282803
geolocation_lng: Unique= False | Null = 0 | Duplicated= 282550
geolocation_city: Unique= False | Null = 0 | Duplicated= 992152
geolocation_state: Unique= False | Null = 0 | Duplicated= 1000136

### Aggregate before you join — order items and payments have many rows per order

In [71]:
# Items Aggregate
items_agg=items_table.groupby("order_id").agg(
    total_price=("price","sum"),
    avg_item_price=("price","mean"),
    max_item_price=("price","max"),
    min_item_price=("price","min"),
    total_freight=("freight_value","sum"),
    total_items=("order_item_id","count"),
    seller_id=("seller_id","first")
).reset_index()
items_agg.head()

,order_id,total_price,avg_item_price,max_item_price,min_item_price,total_freight,total_items,seller_id
0,00010242fe8c5a6d1ba2dd792cb16214,58.90,58.90,58.90,58.90,13.29,1,48436dade18ac8b2bce089ec2a041202
1,00018f77f2f0320c557190d7a144bdd3,239.90,239.90,239.90,239.90,19.93,1,dd7ddc04e1b6c2c614352b383efe2d36
2,000229ec398224ef6ca0657da4fc703e,199.00,199.00,199.00,199.00,17.87,1,5b51032eddd242adc84c38acab88f23d
3,00024acbcdf0a6daa1e931b038114c75,12.99,12.99,12.99,12.99,12.79,1,9d7a1d34a5052409006425275ba1c2b4
4,00042b26cf59d7ce69dfabb4e55b4fd9,199.90,199.90,199.90,199.90,18.14,1,df560393f3a51e74553ab94004ba5c87

In [73]:
# Pyments Aggregate
pyments_agg=pyments_table.groupby("order_id").agg(
    total_pyment_value=("payment_value","sum"),
    max_installments=("payment_installments","max"),
    primary_pyment_type=("payment_type",lambda x: x.mode()[0] if not x.mode().empty else x.iloc[0])
).reset_index()
pyments_agg.head()

,order_id,total_pyment_value,max_installments,primary_pyment_type
0,00010242fe8c5a6d1ba2dd792cb16214,72.19,2,credit_card
1,00018f77f2f0320c557190d7a144bdd3,259.83,3,credit_card
2,000229ec398224ef6ca0657da4fc703e,216.87,5,credit_card
3,00024acbcdf0a6daa1e931b038114c75,25.78,2,credit_card
4,00042b26cf59d7ce69dfabb4e55b4fd9,218.04,3,credit_card

In [ ]:
# Reviews Aggregate
reviews_agg=reviews_table.groupby("order_id").agg(
    avg_review_score=("review_score","mean")
).reset_index()
reviews_agg.head()

                           order_id  avg_review_score
0  00010242fe8c5a6d1ba2dd792cb16214               5.0
1  00018f77f2f0320c557190d7a144bdd3               4.0
2  000229ec398224ef6ca0657da4fc703e               5.0
3  00024acbcdf0a6daa1e931b038114c75               4.0
4  00042b26cf59d7ce69dfabb4e55b4fd9               5.0

### Keep the analysis light here: only what you need to join correctly

In [ ]:
ml_table=orders_table.merge(customers_table,on="customer_id",how="left") \
                     .merge(items_agg,on="order_id",how="left")\
                     .merge(pyments_agg,on="order_id",how="left")\
                     .merge(reviews_agg,on="order_id",how="left")
print(f"The final shape --> {ml_table.shape}")
ml_table.head()

The final shape --> (99441, 23)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,avg_item_price,max_item_price,min_item_price,total_freight,total_items,seller_id,total_pyment_value,max_installments,primary_pyment_type,avg_review_score
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,29.99,29.99,29.99,8.72,1.0,3504c0cb71d7fa48d967e0e4c94d59d9,38.71,1.0,voucher,4.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,...,118.70,118.70,118.70,22.76,1.0,289cdb325fb7e7f891c38608bf9e0962,141.46,1.0,boleto,4.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,159.90,159.90,159.90,19.22,1.0,4869f7a5dfa277a7dca6462dcf3b52b2,179.12,3.0,credit_card,5.0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,7c142cf63193a1473d2e66489a9ae977,59296,...,45.00,45.00,45.00,27.20,1.0,66922902710d126a0e7d26b0e3805106,72.20,1.0,credit_card,5.0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,72632f0f9dd73dfee390c9b22eb56dd6,9195,...,19.90,19.90,19.90,8.72,1.0,2c9e548be18521d1c43cde1c582c6de8,28.62,1.0,credit_card,5.0

### Artifact: one ML table, one row per order

In [ ]:
ml_table.to_csv("olist_ml_dataset.csv",index=False)

In [ ]:
print("=== Artifact Verification ===")
print(f"Total Rows in ML Table: {len(ml_table)}")
print(f"Unique Orders Count: {ml_table['order_id'].nunique()}")
print(f"Is order_id strictly unique? {ml_table['order_id'].is_unique}")

=== Artifact Verification ===
Total Rows in ML Table: 99441
Unique Orders Count: 99441
Is order_id strictly unique? True

In [ ]:
print(f"\nArtifact Shape: {ml_table.shape}")
ml_table.head()

Artifact Shape: (99441, 23)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,avg_item_price,max_item_price,min_item_price,total_freight,total_items,seller_id,total_pyment_value,max_installments,primary_pyment_type,avg_review_score
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,29.99,29.99,29.99,8.72,1.0,3504c0cb71d7fa48d967e0e4c94d59d9,38.71,1.0,voucher,4.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,...,118.70,118.70,118.70,22.76,1.0,289cdb325fb7e7f891c38608bf9e0962,141.46,1.0,boleto,4.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,159.90,159.90,159.90,19.22,1.0,4869f7a5dfa277a7dca6462dcf3b52b2,179.12,3.0,credit_card,5.0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,7c142cf63193a1473d2e66489a9ae977,59296,...,45.00,45.00,45.00,27.20,1.0,66922902710d126a0e7d26b0e3805106,72.20,1.0,credit_card,5.0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,72632f0f9dd73dfee390c9b22eb56dd6,9195,...,19.90,19.90,19.90,8.72,1.0,2c9e548be18521d1c43cde1c582c6de8,28.62,1.0,credit_card,5.0